{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Namespace(alpha=0.999, aug='1st', batch_size=32, beta1=0.9, beta2=0.999, clip_norm=1.0, cv=False, dataset='dgl', degree_embedding_size=16, epochs=100, exp='Pretrain', finetune=False, fold_idx=0, freq_embedding_size=16, gpu=0, hidden_size=64, learning_rate=0.005, load_path=None, lr_decay_epochs=[120, 160, 200], lr_decay_rate=0.0, max_degree=512, max_edge_freq=16, max_node_freq=16, moco=True, model='gin', model_folder='saved/Pretrain_moco_True_dgl_gin_layer_5_lr_0.005_decay_1e-05_bsz_32_hid_64_samples_2000_nce_t_0.07_nce_k_1024_rw_hops_256_restart_prob_0.8_aug_1st_ft_False_deg_16_pos_32_momentum_0.999', model_name='Pretrain_moco_True_dgl_gin_layer_5_lr_0.005_decay_1e-05_bsz_32_hid_64_samples_2000_nce_t_0.07_nce_k_1024_rw_hops_256_restart_prob_0.8_aug_1st_ft_False_deg_16_pos_32_momentum_0.999', model_path='saved', momentum=0.9, nce_k=1024, nce_t=0.07, norm=True, num_copies=6, num_layer=5, num_samples=2000, num_workers=12, optimizer='adam', positional_embedding_size=32, print_freq=10, readout='avg', restart_prob=0.8, resume='', rw_hops=256, save_freq=1, seed=0, set2set_iter=6, set2set_lstm_layer=3, subgraph_size=128, tb_folder='tensorboard/Pretrain_moco_True_dgl_gin_layer_5_lr_0.005_decay_1e-05_bsz_32_hid_64_samples_2000_nce_t_0.07_nce_k_1024_rw_hops_256_restart_prob_0.8_aug_1st_ft_False_deg_16_pos_32_momentum_0.999', tb_freq=250, tb_path='tensorboard', weight_decay=1e-05)\n",
      "Use GPU: 0 for training\n",
      "setting random seeds\n",
      "before construct dataset 22.786346435546875\n",
      "Traceback (most recent call last):\n",
      "  File \"train.py\", line 818, in <module>\n",
      "    main(args)\n",
      "  File \"train.py\", line 548, in main\n",
      "    train_dataset = LoadBalanceGraphDataset(\n",
      "  File \"/home/shakir/simplical_complices_gcc/gcc/datasets/graph_dataset.py\", line 59, in __init__\n",
      "    graph_sizes = dgl.data.utils.load_labels(dgl_graphs_file)[\n",
      "  File \"/home/shakir/.venv/lib/python3.8/site-packages/dgl/data/graph_serialize.py\", line 248, in load_labels\n",
      "    version = _CAPI_GetFileVersion(filename)\n",
      "  File \"dgl/_ffi/_cython/./function.pxi\", line 295, in dgl._ffi._cy3.core.FunctionBase.__call__\n",
      "  File \"dgl/_ffi/_cython/./function.pxi\", line 227, in dgl._ffi._cy3.core.FuncCall\n",
      "  File \"dgl/_ffi/_cython/./function.pxi\", line 217, in dgl._ffi._cy3.core.FuncCall3\n",
      "dgl._ffi.base.DGLError: [15:45:39] /opt/dgl/src/graph/serialize/graph_serialize.cc:128: Check failed: magicNum == kDGLSerializeMagic (5789751444030890300 vs. 15937764024707752255) : Invalid DGL files\n",
      "Stack trace:\n",
      "  [bt] (0) /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x75) [0x7fbf74ab0a55]\n",
      "  [bt] (1) /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so(dgl::serialize::GetFileVersion(std::string const&)+0x121) [0x7fbf74f35a01]\n",
      "  [bt] (2) /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so(+0x80bb50) [0x7fbf74f35b50]\n",
      "  [bt] (3) /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so(DGLFuncCall+0x48) [0x7fbf74e3ea48]\n",
      "  [bt] (4) /home/shakir/.venv/lib/python3.8/site-packages/dgl/_ffi/_cy3/core.cpython-38-x86_64-linux-gnu.so(+0x16843) [0x7fbf64e8d843]\n",
      "  [bt] (5) /home/shakir/.venv/lib/python3.8/site-packages/dgl/_ffi/_cy3/core.cpython-38-x86_64-linux-gnu.so(+0x1705b) [0x7fbf64e8e05b]\n",
      "  [bt] (6) python(_PyObject_MakeTpCall+0x29e) [0x5f3e1e]\n",
      "  [bt] (7) python(_PyEval_EvalFrameDefault+0x58e6) [0x570266]\n",
      "  [bt] (8) python(_PyFunction_Vectorcall+0x1b6) [0x5f6836]\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "!bash scripts/pretrain.sh 0 --moco --nce-k 1024\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "tensor([1, 2, 1]) hello tensor([2, 4, 3]) 10\n",
      "tensor([[ 9],\n",
      "        [99],\n",
      "        [19]])\n",
      "tensor([2, 4, 3])\n",
      "tensor([1, 2, 1])\n"
     ]
    }
   ],
   "source": [
    "import torch\n",
    "import dgl\n",
    "import dgl.sparse as dglsp\n",
    "\n",
    "\n",
    "indices = torch.tensor([[1, 2, 1], [2, 4, 3]])\n",
    "A = dglsp.spmatrix(indices,torch.tensor([[9],[99],[19]]))\n",
    "a , b , c = *A.coo() , 10\n",
    "print(a,'hello',b , c)\n",
    "print(A.val)\n",
    "print(A.col)\n",
    "print(A.row)\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "========= COMPUTE-SANITIZER\n",
      "Namespace(alpha=0.999, aug='1st', batch_size=32, beta1=0.9, beta2=0.999, clip_norm=1.0, cv=False, dataset='imdb-binary', degree_embedding_size=16, epochs=1, exp='Pretrain', finetune=False, fold_idx=0, freq_embedding_size=16, gpu=1, hidden_size=64, learning_rate=0.005, load_path=None, lr_decay_epochs=[120, 160, 200], lr_decay_rate=0.0, max_degree=512, max_edge_freq=16, max_node_freq=16, moco=True, model='gin', model_folder='saved/Pretrain_moco_True_imdb-binary_gin_layer_5_lr_0.005_decay_1e-05_bsz_32_hid_64_samples_10_nce_t_0.07_nce_k_32_rw_hops_64_restart_prob_0.8_aug_1st_ft_False_deg_16_pos_32_momentum_0.999', model_name='Pretrain_moco_True_imdb-binary_gin_layer_5_lr_0.005_decay_1e-05_bsz_32_hid_64_samples_10_nce_t_0.07_nce_k_32_rw_hops_64_restart_prob_0.8_aug_1st_ft_False_deg_16_pos_32_momentum_0.999', model_path='saved', momentum=0.9, nce_k=32, nce_t=0.07, norm=True, num_copies=1, num_layer=5, num_samples=10, num_workers=1, optimizer='adam', positional_embedding_size=32, print_freq=10, readout='avg', restart_prob=0.8, resume='', rw_hops=64, save_freq=1, seed=0, set2set_iter=6, set2set_lstm_layer=3, subgraph_size=128, tb_folder='tensorboard/Pretrain_moco_True_imdb-binary_gin_layer_5_lr_0.005_decay_1e-05_bsz_32_hid_64_samples_10_nce_t_0.07_nce_k_32_rw_hops_64_restart_prob_0.8_aug_1st_ft_False_deg_16_pos_32_momentum_0.999', tb_freq=250, tb_path='tensorboard', weight_decay=1e-05)\n",
      "Use GPU: 1 for training\n",
      "setting random seeds\n",
      "before construct dataset 86.95321655273438\n",
      "before construct dataloader 86.97124099731445\n",
      "before training 86.97124099731445\n",
      "memorymoco1\n",
      "using queue shape: (32,64)\n",
      "==> training...\n",
      "moco1\n",
      "moco2\n",
      "moco3\n",
      "moco4\n",
      "<torch.utils.data.dataloader.DataLoader object at 0x7fd3e83fefd0>\n",
      "k<torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fd3e837abb0>\n",
      "<torch.utils.data.dataloader.DataLoader object at 0x7fd3e83fefd0>\n",
      "moco5\n",
      "graph_q:Graph(num_nodes=764, num_edges=14672,\n",
      "      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), 'pos_undirected': Scheme(shape=(32,), dtype=torch.float32), 'seed': Scheme(shape=(), dtype=torch.int64)}\n",
      "      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)})\n",
      "graph_q:Graph(num_nodes=764, num_edges=14672,\n",
      "      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), '_TYPE': Scheme(shape=(), dtype=torch.int64)}\n",
      "      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), '_TYPE': Scheme(shape=(), dtype=torch.int64)}) graph_q.is_homogeneous:True\n",
      "gpu:1\n",
      "graph_q on devicecpu\n",
      "cuda:1\n",
      "========= Program hit cudaErrorLaunchFailure (error 719) due to \"unspecified launch failure\" on CUDA API call to cudaMemcpyAsync.\n",
      "=========     Saved host backtrace up to driver entry point at error\n",
      "=========     Host Frame: [0x423cf6]\n",
      "=========                in /lib/x86_64-linux-gnu/libcuda.so.1\n",
      "=========     Host Frame:cudaMemcpyAsync [0x1459ab4]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so\n",
      "=========     Host Frame:dgl::runtime::CUDADeviceAPI::CopyDataFromTo(void const*, unsigned long, void*, unsigned long, unsigned long, DGLContext, DGLContext, DGLDataType) [0x8bbce6]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so\n",
      "=========     Host Frame:dgl::runtime::NDArray::CopyFromTo(DGLArray*, DGLArray*) [0x7315ed]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so\n",
      "=========     Host Frame:dgl::runtime::NDArray::CopyTo(DGLContext const&) const [0x76ccd3]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so\n",
      "=========     Host Frame:dgl::UnitGraph::CopyTo(std::shared_ptr<dgl::BaseHeteroGraph>, DGLContext const&) [0x87a38f]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so\n",
      "=========     Host Frame:dgl::HeteroGraph::CopyTo(std::shared_ptr<dgl::BaseHeteroGraph>, DGLContext const&) [0x77e0f6]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so\n",
      "=========     Host Frame:std::_Function_handler<void (dgl::runtime::DGLArgs, dgl::runtime::DGLRetValue*), dgl::{lambda(dgl::runtime::DGLArgs, dgl::runtime::DGLRetValue*)#47}>::_M_invoke(std::_Any_data const&, dgl::runtime::DGLArgs&&, dgl::runtime::DGLRetValue*&&) [0x78d496]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so\n",
      "=========     Host Frame:DGLFuncCall [0x714a48]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so\n",
      "=========     Host Frame:dgl/_ffi/_cython/core.cpp:6710:__pyx_f_3dgl_4_ffi_4_cy3_4core_FuncCall(void*, _object*, DGLValue*, int*) [0x16843]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/dgl/_ffi/_cy3/core.cpython-38-x86_64-linux-gnu.so\n",
      "=========     Host Frame:dgl/_ffi/_cython/core.cpp:7660:__pyx_pw_3dgl_4_ffi_4_cy3_4core_12FunctionBase_5__call__(_object*, _object*, _object*) [0x1705b]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/dgl/_ffi/_cy3/core.cpython-38-x86_64-linux-gnu.so\n",
      "=========     Host Frame:_PyObject_MakeTpCall [0x1f3e1e]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame:_PyEval_EvalFrameDefault [0x170266]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame: [0x10a92e]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame:_PyEval_EvalFrameDefault [0x170035]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame:_PyEval_EvalCodeWithName [0x16939a]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame:_PyFunction_Vectorcall [0x1f6a13]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame:_PyEval_EvalFrameDefault [0x16b1da]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame:_PyFunction_Vectorcall [0x1f6836]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame:_PyEval_EvalFrameDefault [0x16b0ae]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame:_PyEval_EvalCodeWithName [0x16939a]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame:_PyFunction_Vectorcall [0x1f6a13]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame:_PyEval_EvalFrameDefault [0x16b0ae]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame:_PyEval_EvalCodeWithName [0x16939a]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame:PyEval_EvalCode [0x28d047]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame: [0x27e351]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame: [0x27e3cf]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame: [0x27e471]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame:PyRun_SimpleFileExFlags [0x27e817]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame:Py_RunMain [0x2b6fe2]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame:Py_BytesMain [0x2b736d]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "=========     Host Frame:../csu/libc-start.c:342:__libc_start_main [0x24083]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:_start [0x1fa5ce]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "========= \n",
      "Traceback (most recent call last):\n",
      "  File \"train.py\", line 852, in <module>\n",
      "    main(args)\n",
      "  File \"train.py\", line 767, in main\n",
      "    loss = train_moco(\n",
      "  File \"train.py\", line 413, in train_moco\n",
      "    graph_q = graph_q.to(torch.device('cuda',opt.gpu))\n",
      "  File \"/home/shakir/.venv/lib/python3.8/site-packages/dgl/heterograph.py\", line 5709, in to\n",
      "    ret._graph = self._graph.copy_to(utils.to_dgl_context(device))\n",
      "  File \"/home/shakir/.venv/lib/python3.8/site-packages/dgl/heterograph_index.py\", line 255, in copy_to\n",
      "    return _CAPI_DGLHeteroCopyTo(self, ctx.device_type, ctx.device_id)\n",
      "  File \"dgl/_ffi/_cython/./function.pxi\", line 295, in dgl._ffi._cy3.core.FunctionBase.__call__\n",
      "  File \"dgl/_ffi/_cython/./function.pxi\", line 227, in dgl._ffi._cy3.core.FuncCall\n",
      "  File \"dgl/_ffi/_cython/./function.pxi\", line 217, in dgl._ffi._cy3.core.FuncCall3\n",
      "dgl._ffi.base.DGLError: [13:45:57] /opt/dgl/src/runtime/cuda/cuda_device_api.cc:343: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: CUDA: unspecified launch failure\n",
      "Stack trace:\n",
      "  [bt] (0) /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so(+0x8b9655) [0x7fd461ccc655]\n",
      "  [bt] (1) /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so(dgl::runtime::CUDADeviceAPI::CopyDataFromTo(void const*, unsigned long, void*, unsigned long, unsigned long, DGLContext, DGLContext, DGLDataType)+0x82) [0x7fd461cceaf2]\n",
      "  [bt] (2) /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::CopyFromTo(DGLArray*, DGLArray*)+0x10d) [0x7fd461b445ed]\n",
      "  [bt] (3) /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::CopyTo(DGLContext const&) const+0x103) [0x7fd461b7fcd3]\n",
      "  [bt] (4) /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so(dgl::UnitGraph::CopyTo(std::shared_ptr<dgl::BaseHeteroGraph>, DGLContext const&)+0x3ef) [0x7fd461c8d38f]\n",
      "  [bt] (5) /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so(dgl::HeteroGraph::CopyTo(std::shared_ptr<dgl::BaseHeteroGraph>, DGLContext const&)+0xf6) [0x7fd461b910f6]\n",
      "  [bt] (6) /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so(+0x78d496) [0x7fd461ba0496]\n",
      "  [bt] (7) /home/shakir/.venv/lib/python3.8/site-packages/dgl/libdgl.so(DGLFuncCall+0x48) [0x7fd461b27a48]\n",
      "  [bt] (8) /home/shakir/.venv/lib/python3.8/site-packages/dgl/_ffi/_cy3/core.cpython-38-x86_64-linux-gnu.so(+0x16843) [0x7fd451b76843]\n",
      "\n",
      "\n",
      "========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to \"unspecified launch failure\" on CUDA API call to cuModuleUnload.\n",
      "=========     Saved host backtrace up to driver entry point at error\n",
      "=========     Host Frame: [0x28e5ad]\n",
      "=========                in /lib/x86_64-linux-gnu/libcuda.so.1\n",
      "=========     Host Frame: [0x41d2ee]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x41f43c]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x4202bf]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x411ad2]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x412335]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/exit.c:109:__run_exit_handlers [0x468a7]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/on_exit.c:26:on_exit [0x46a60]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:../csu/libc-start.c:261:__libc_start_main [0x2408a]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:_start [0x1fa5ce]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "========= \n",
      "========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to \"unspecified launch failure\" on CUDA API call to cuModuleUnload.\n",
      "=========     Saved host backtrace up to driver entry point at error\n",
      "=========     Host Frame: [0x28e5ad]\n",
      "=========                in /lib/x86_64-linux-gnu/libcuda.so.1\n",
      "=========     Host Frame: [0x41d2ee]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x41f43c]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x4202bf]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x411ad2]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x412335]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/exit.c:109:__run_exit_handlers [0x468a7]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/on_exit.c:26:on_exit [0x46a60]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:../csu/libc-start.c:261:__libc_start_main [0x2408a]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:_start [0x1fa5ce]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "========= \n",
      "========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to \"unspecified launch failure\" on CUDA API call to cuModuleUnload.\n",
      "=========     Saved host backtrace up to driver entry point at error\n",
      "=========     Host Frame: [0x28e5ad]\n",
      "=========                in /lib/x86_64-linux-gnu/libcuda.so.1\n",
      "=========     Host Frame: [0x41d2ee]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x41f43c]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x4202bf]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x411ad2]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x412335]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/exit.c:109:__run_exit_handlers [0x468a7]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/on_exit.c:26:on_exit [0x46a60]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:../csu/libc-start.c:261:__libc_start_main [0x2408a]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:_start [0x1fa5ce]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "========= \n",
      "========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to \"unspecified launch failure\" on CUDA API call to cuModuleUnload.\n",
      "=========     Saved host backtrace up to driver entry point at error\n",
      "=========     Host Frame: [0x28e5ad]\n",
      "=========                in /lib/x86_64-linux-gnu/libcuda.so.1\n",
      "=========     Host Frame: [0x41d2ee]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x41f43c]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x4202bf]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x411ad2]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x412335]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/exit.c:109:__run_exit_handlers [0x468a7]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/on_exit.c:26:on_exit [0x46a60]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:../csu/libc-start.c:261:__libc_start_main [0x2408a]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:_start [0x1fa5ce]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "========= \n",
      "========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to \"unspecified launch failure\" on CUDA API call to cuModuleUnload.\n",
      "=========     Saved host backtrace up to driver entry point at error\n",
      "=========     Host Frame: [0x28e5ad]\n",
      "=========                in /lib/x86_64-linux-gnu/libcuda.so.1\n",
      "=========     Host Frame: [0x41d2ee]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x41f43c]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x4202bf]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x411ad2]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x412335]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/exit.c:109:__run_exit_handlers [0x468a7]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/on_exit.c:26:on_exit [0x46a60]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:../csu/libc-start.c:261:__libc_start_main [0x2408a]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:_start [0x1fa5ce]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "========= \n",
      "========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to \"unspecified launch failure\" on CUDA API call to cuModuleUnload.\n",
      "=========     Saved host backtrace up to driver entry point at error\n",
      "=========     Host Frame: [0x28e5ad]\n",
      "=========                in /lib/x86_64-linux-gnu/libcuda.so.1\n",
      "=========     Host Frame: [0x41d2ee]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x41f43c]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x4202bf]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x411ad2]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x412335]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/exit.c:109:__run_exit_handlers [0x468a7]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/on_exit.c:26:on_exit [0x46a60]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:../csu/libc-start.c:261:__libc_start_main [0x2408a]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:_start [0x1fa5ce]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "========= \n",
      "========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to \"unspecified launch failure\" on CUDA API call to cuModuleUnload.\n",
      "=========     Saved host backtrace up to driver entry point at error\n",
      "=========     Host Frame: [0x28e5ad]\n",
      "=========                in /lib/x86_64-linux-gnu/libcuda.so.1\n",
      "=========     Host Frame: [0x41d2ee]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x41f43c]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x4202bf]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x411ad2]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x412335]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/exit.c:109:__run_exit_handlers [0x468a7]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/on_exit.c:26:on_exit [0x46a60]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:../csu/libc-start.c:261:__libc_start_main [0x2408a]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:_start [0x1fa5ce]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "========= \n",
      "========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to \"unspecified launch failure\" on CUDA API call to cuModuleUnload.\n",
      "=========     Saved host backtrace up to driver entry point at error\n",
      "=========     Host Frame: [0x28e5ad]\n",
      "=========                in /lib/x86_64-linux-gnu/libcuda.so.1\n",
      "=========     Host Frame: [0x41d2ee]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x41f43c]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x4202bf]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x411ad2]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x412335]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/exit.c:109:__run_exit_handlers [0x468a7]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/on_exit.c:26:on_exit [0x46a60]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:../csu/libc-start.c:261:__libc_start_main [0x2408a]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:_start [0x1fa5ce]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "========= \n",
      "========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to \"unspecified launch failure\" on CUDA API call to cuModuleUnload.\n",
      "=========     Saved host backtrace up to driver entry point at error\n",
      "=========     Host Frame: [0x28e5ad]\n",
      "=========                in /lib/x86_64-linux-gnu/libcuda.so.1\n",
      "=========     Host Frame: [0x41d2ee]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x41f43c]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x4202bf]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x411ad2]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x412335]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/exit.c:109:__run_exit_handlers [0x468a7]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/on_exit.c:26:on_exit [0x46a60]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:../csu/libc-start.c:261:__libc_start_main [0x2408a]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:_start [0x1fa5ce]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "========= \n",
      "========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to \"unspecified launch failure\" on CUDA API call to cuModuleUnload.\n",
      "=========     Saved host backtrace up to driver entry point at error\n",
      "=========     Host Frame: [0x28e5ad]\n",
      "=========                in /lib/x86_64-linux-gnu/libcuda.so.1\n",
      "=========     Host Frame: [0x41d2ee]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x41f43c]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x4202bf]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x411ad2]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x412335]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/exit.c:109:__run_exit_handlers [0x468a7]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/on_exit.c:26:on_exit [0x46a60]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:../csu/libc-start.c:261:__libc_start_main [0x2408a]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:_start [0x1fa5ce]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "========= \n",
      "========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to \"unspecified launch failure\" on CUDA API call to cuModuleUnload.\n",
      "=========     Saved host backtrace up to driver entry point at error\n",
      "=========     Host Frame: [0x28e5ad]\n",
      "=========                in /lib/x86_64-linux-gnu/libcuda.so.1\n",
      "=========     Host Frame: [0x41d2ee]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x41f43c]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x4202bf]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x411ad2]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x412335]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/exit.c:109:__run_exit_handlers [0x468a7]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/on_exit.c:26:on_exit [0x46a60]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:../csu/libc-start.c:261:__libc_start_main [0x2408a]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:_start [0x1fa5ce]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "========= \n",
      "========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to \"unspecified launch failure\" on CUDA API call to cuModuleUnload.\n",
      "=========     Saved host backtrace up to driver entry point at error\n",
      "=========     Host Frame: [0x28e5ad]\n",
      "=========                in /lib/x86_64-linux-gnu/libcuda.so.1\n",
      "=========     Host Frame: [0x41d2ee]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x41f43c]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x4202bf]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x411ad2]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x412335]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/exit.c:109:__run_exit_handlers [0x468a7]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/on_exit.c:26:on_exit [0x46a60]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:../csu/libc-start.c:261:__libc_start_main [0x2408a]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:_start [0x1fa5ce]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "========= \n",
      "========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to \"unspecified launch failure\" on CUDA API call to cuModuleUnload.\n",
      "=========     Saved host backtrace up to driver entry point at error\n",
      "=========     Host Frame: [0x28e5ad]\n",
      "=========                in /lib/x86_64-linux-gnu/libcuda.so.1\n",
      "=========     Host Frame: [0x41d2ee]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x41f43c]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x4202bf]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x411ad2]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x412335]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/exit.c:109:__run_exit_handlers [0x468a7]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/on_exit.c:26:on_exit [0x46a60]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:../csu/libc-start.c:261:__libc_start_main [0x2408a]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:_start [0x1fa5ce]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "========= \n",
      "========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to \"unspecified launch failure\" on CUDA API call to cuModuleUnload.\n",
      "=========     Saved host backtrace up to driver entry point at error\n",
      "=========     Host Frame: [0x28e5ad]\n",
      "=========                in /lib/x86_64-linux-gnu/libcuda.so.1\n",
      "=========     Host Frame: [0x41d2ee]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x41f43c]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x4202bf]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x411ad2]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x412335]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/exit.c:109:__run_exit_handlers [0x468a7]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/on_exit.c:26:on_exit [0x46a60]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:../csu/libc-start.c:261:__libc_start_main [0x2408a]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:_start [0x1fa5ce]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "========= \n",
      "========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to \"unspecified launch failure\" on CUDA API call to cuModuleUnload.\n",
      "=========     Saved host backtrace up to driver entry point at error\n",
      "=========     Host Frame: [0x28e5ad]\n",
      "=========                in /lib/x86_64-linux-gnu/libcuda.so.1\n",
      "=========     Host Frame: [0x41d2ee]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x41f43c]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x4202bf]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x411ad2]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x412335]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/exit.c:109:__run_exit_handlers [0x468a7]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/on_exit.c:26:on_exit [0x46a60]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:../csu/libc-start.c:261:__libc_start_main [0x2408a]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:_start [0x1fa5ce]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "========= \n",
      "========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to \"unspecified launch failure\" on CUDA API call to cuModuleUnload.\n",
      "=========     Saved host backtrace up to driver entry point at error\n",
      "=========     Host Frame: [0x28e5ad]\n",
      "=========                in /lib/x86_64-linux-gnu/libcuda.so.1\n",
      "=========     Host Frame: [0x41d2ee]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x41f43c]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x4202bf]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x411ad2]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x412335]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/exit.c:109:__run_exit_handlers [0x468a7]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/on_exit.c:26:on_exit [0x46a60]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:../csu/libc-start.c:261:__libc_start_main [0x2408a]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:_start [0x1fa5ce]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "========= \n",
      "========= Program hit CUDA_ERROR_LAUNCH_FAILED (error 719) due to \"unspecified launch failure\" on CUDA API call to cuModuleUnload.\n",
      "=========     Saved host backtrace up to driver entry point at error\n",
      "=========     Host Frame: [0x28e5ad]\n",
      "=========                in /lib/x86_64-linux-gnu/libcuda.so.1\n",
      "=========     Host Frame: [0x41d2ee]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x41f43c]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x4202bf]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x411ad2]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame: [0x412335]\n",
      "=========                in /home/shakir/.venv/lib/python3.8/site-packages/torch/lib/libcudnn_ops_infer.so.8\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/exit.c:109:__run_exit_handlers [0x468a7]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:/build/glibc-SzIz7B/glibc-2.31/stdlib/on_exit.c:26:on_exit [0x46a60]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:../csu/libc-start.c:261:__libc_start_main [0x2408a]\n",
      "=========                in /lib/x86_64-linux-gnu/libc.so.6\n",
      "=========     Host Frame:_start [0x1fa5ce]\n",
      "=========                in /home/shakir/.venv/bin/python\n",
      "========= \n",
      "========= Target application returned an error\n",
      "========= ERROR SUMMARY: 18 errors\n"
     ]
    }
   ],
   "source": [
    "! bash scripts/pretrain.sh 1  --moco --nce-k 32  --num-workers 1 --num-copies 1  --dataset 'imdb-binary' --epochs 1 --num-samples 10 --rw-hops 64\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
