137969 739384
/home/shakir/.venv/lib/python3.8/site-packages/dgl/data/graph_serialize.py:189: DGLWarning: You are loading a graph file saved by old version of dgl.              Please consider saving it again with the current format.
  dgl_warning(
Traceback (most recent call last):
  File "get_pretrain_faces.py", line 9, in <module>
    pretrain_based(gs,'dgl')
  File "/home/shakir/simplical_complices_gcc/simplex_lists/helpers.py", line 64, in pretrain_based
    b1,b2,faces = compute_hodge_matrix_2(g2.num_nodes(),g2.edges())
  File "/home/shakir/simplical_complices_gcc/simplex_lists/helpers.py", line 26, in compute_hodge_matrix_2
    B1, B2 = incidence_matrices(g, sorted(g.nodes), sorted(g.edges), faces, edge_to_idx)
  File "/home/shakir/simplical_complices_gcc/simplex_lists/incidence_matrix.py", line 57, in incidence_matrices
    B1 = np.array(nx.incidence_matrix(G, nodelist=V, edgelist=E, oriented=True).todense())
  File "/home/shakir/.venv/lib/python3.8/site-packages/scipy/sparse/_base.py", line 946, in todense
    return self._ascontainer(self.toarray(order=order, out=out))
  File "/home/shakir/.venv/lib/python3.8/site-packages/scipy/sparse/_compressed.py", line 1051, in toarray
    out = self._process_toarray_args(order, out)
  File "/home/shakir/.venv/lib/python3.8/site-packages/scipy/sparse/_base.py", line 1298, in _process_toarray_args
    return np.zeros(self.shape, dtype=self.dtype, order=order)
numpy.core._exceptions.MemoryError: Unable to allocate 380. GiB for an array with shape (137969, 369692) and data type float64
